/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'MintableERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MintableERC20__factory>
getContractFactory(name: 'Presale', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Presale__factory>
getContractFactory(name: 'PresaleFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PresaleFactory__factory>

  getContractAt(name: 'MintableERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MintableERC20>
getContractAt(name: 'Presale', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Presale>
getContractAt(name: 'PresaleFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PresaleFactory>

  deployContract(name: 'MintableERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MintableERC20>
deployContract(name: 'Presale', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Presale>
deployContract(name: 'PresaleFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PresaleFactory>

  deployContract(name: 'MintableERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MintableERC20>
deployContract(name: 'Presale', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Presale>
deployContract(name: 'PresaleFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PresaleFactory>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  